responsive layout + animations + fixed issues
Shitikyan/Quantum pull request #1
Opened 2023-11-22 16:53 UTC by Shitikyan

2023-11-22 17:12 UTC, Shitikyan commented on quantum-be/src/telnyxService.js
> +  console.log("????????????");
delete

2023-11-22 17:12 UTC, Shitikyan commented on quantum/public/particles.js-master/.jshintrc
why do you need this file? `dist` folder is generating during build, so it must be in `gitignore` file.

2023-11-22 17:12 UTC, Shitikyan commented on quantum/public/particles.js-master/.travis.yml
why do you need this file?

2023-11-22 17:12 UTC, Shitikyan commented on quantum/public/particles.js-master/LICENSE
delete

2023-11-22 17:12 UTC, Shitikyan commented on quantum/public/particles.js-master/dist/particles.js
why do you need this file?

2023-11-22 17:12 UTC, Shitikyan commented on quantum/public/particles.js-master/dist/particles.min.js
what is this?

2023-11-22 17:12 UTC, Shitikyan commented on quantum/public/particles.js-master/gulpfile.js
check careful whole `particles.js-master` folder

2023-11-23 23:09 UTC, SergeyG-Solicy requested changes

2023-11-23 23:09 UTC, SergeyG-Solicy commented on quantum-be/src/Services/telnyxService.js
> +    console.log(message);
delete

2023-11-23 23:09 UTC, SergeyG-Solicy commented on quantum/src/services/userService.ts
> +  public async signin(body: IUser): Promise<string | AxiosError> {
must be `signup`

2023-11-23 23:11 UTC, merged